# Generated by Django 4.2.16 on 2026-03-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
    ]
