# Generated by Django 4.2.16 on 2026-03-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_document_error_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_status_3c11ef_idx',
            old_name='projects_status_95fcb9_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_owner_i_9f3020_idx',
            old_name='projects_owner_a4f8a3_idx',
        ),
    ]
