"""URL configuration for NER API endpoints."""

from django.urls import path
from . import views

urlpatterns = [
    path('admin/entity-labels/', views.EntityLabelAdminView.as_view(), name='admin-entity-labels'),
    path('admin/entity-labels/<uuid:id>/', views.EntityLabelAdminDetailView.as_view(), name='admin-entity-labels-detail'),
    path('admin/relationship-types/', views.RelationshipTypeAdminView.as_view(), name='admin-relationship-types'),
    path('admin/relationship-types/<uuid:id>/', views.RelationshipTypeAdminDetailView.as_view(), name='admin-relationship-types-detail'),
    path('documents/<uuid:id>/extract-entities/', views.ExtractEntitiesView.as_view(), name='extract-entities'),
    path('documents/<uuid:id>/extract-entities-relations/', views.ExtractEntitiesRelationsView.as_view(), name='extract-entities-relations'),
    path('documents/<uuid:id>/extract-relations/', views.ExtractRelationsOnlyView.as_view(), name='extract-relations-only'),
    path('documents/<uuid:id>/entities/', views.DocumentEntitiesView.as_view(), name='document-entities'),
    path('documents/<uuid:id>/entities/review-candidates/', views.EntityReviewCandidatesView.as_view(), name='entity-review-candidates'),
    path('documents/<uuid:id>/entities/review-candidates/<uuid:candidate_id>/resolve/', views.EntityReviewResolveView.as_view(), name='entity-review-resolve'),
    path('documents/<uuid:id>/relations/', views.RelationsView.as_view(), name='document-relations'),
    path('documents/<uuid:id>/runs/', views.DocumentRunsView.as_view(), name='document-runs'),
    path('documents/<uuid:id>/extraction-progress/', views.ExtractionProgressView.as_view(), name='extraction-progress'),
    path('projects/<uuid:id>/extract-entities/', views.ProjectExtractEntitiesView.as_view(), name='project-extract-entities'),
    path('projects/<uuid:id>/entities/', views.ProjectEntitiesView.as_view(), name='project-entities'),
    path('projects/<uuid:id>/graph/', views.ProjectGraphView.as_view(), name='project-graph'),
    path('projects/<uuid:id>/query/', views.ProjectQueryView.as_view(), name='project-query'),
    path('entities/flagged/', views.UserFlaggedEntitiesView.as_view(), name='user-flagged-entities'),
    path('entities/', views.GlobalEntityListView.as_view(), name='global-entity-list'),
    path('entities/<uuid:id>/', views.GlobalEntityProfileView.as_view(), name='global-entity-profile'),
    path('entities/<uuid:id>/profile/', views.EntityProfileView.as_view(), name='entity-profile'),
    path('entities/<uuid:id>/summary/', views.EntitySummaryView.as_view(), name='entity-summary'),
    path('entities/<uuid:id>/flag/', views.EntityFlagView.as_view(), name='entity-flag'),
    path('entities/<uuid:id>/timeline/', views.EntityTimelineView.as_view(), name='entity-timeline'),
    path('projects/<uuid:id>/flagged-count/', views.ProjectFlaggedCountView.as_view(), name='project-flagged-count'),
    path('projects/<uuid:id>/review/', views.DeduplicationReviewListView.as_view(), name='project-dedup-review'),
    path('projects/<uuid:id>/providers/', views.ProjectProviderView.as_view(), name='project-providers'),
    path('review-candidates/<uuid:id>/resolve/', views.ReviewCandidateResolveView.as_view(), name='review-candidate-resolve'),
    path('graph/', views.GraphNodesView.as_view(), name='graph-nodes'),
    path('projects/<uuid:id>/export/entities.csv', views.ProjectExportEntitiesCSVView.as_view(), name='project-export-entities-csv'),
    path('projects/<uuid:id>/export/relations.csv', views.ProjectExportRelationsCSVView.as_view(), name='project-export-relations-csv'),
    path('projects/<uuid:id>/export/report.docx', views.ProjectExportReportDOCXView.as_view(), name='project-export-report-docx'),
    path('projects/<uuid:id>/export/report.pdf', views.ProjectExportReportPDFView.as_view(), name='project-export-report-pdf'),
]
