# Generated by Django 4.2.16 on 2026-03-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entity',
            new_name='ner_entity_documen_d36b1b_idx',
            old_name='ner_entity_document_id_entity_type_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='ner_entity_documen_6b466a_idx',
            old_name='ner_entity_document_id_confidence_idx',
        ),
    ]
