# Generated by Django 4.2.16 on 2026-03-14

import uuid
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('ner', '0002_rename_ner_entity_document_id_entity_type_idx_ner_entity_documen_d36b1b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NERRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('tokens_cached', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ner_runs', to='ingestion.document')),
            ],
            options={
                'db_table': 'ner_run',
            },
        ),
        migrations.AddIndex(
            model_name='nerrun',
            index=models.Index(fields=['document_id', 'created_at'], name='ner_run_documen_8aaea4_idx'),
        ),
        migrations.AddIndex(
            model_name='nerrun',
            index=models.Index(fields=['provider', 'model'], name='ner_run_provider_85ea67_idx'),
        ),
        migrations.AddField(
            model_name='entity',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='ner.nerrun'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('canonical_name', 'document_id', 'entity_type', 'run')},
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['run', 'entity_type'], name='ner_entity_run_id_7f8c75_idx'),
        ),
    ]
