# Generated by Django 4.2.16 on 2026-03-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0003_ner_run'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entity',
            new_name='ner_entity_run_id_572735_idx',
            old_name='ner_entity_run_id_7f8c75_idx',
        ),
        migrations.RenameIndex(
            model_name='nerrun',
            new_name='ner_run_documen_8d7f39_idx',
            old_name='ner_run_documen_8aaea4_idx',
        ),
        migrations.RenameIndex(
            model_name='nerrun',
            new_name='ner_run_provide_530c14_idx',
            old_name='ner_run_provider_85ea67_idx',
        ),
    ]
