# Generated by Django 4.2.16 on 2026-03-19 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0015_contextual_entity_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityreviewcandidate',
            name='similarity_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
