# Generated by Django 5.2.8 on 2026-04-17 06:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0014_document_extraction_state_and_clean_text'),
        ('ner', '0027_entity_mention_and_relation_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stakeholderpersona',
            options={'ordering': ['entity_type__name']},
        ),
        migrations.AlterField(
            model_name='entitymention',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('flag', 'Flag for Review')], max_length=16)),
                ('context_type', models.CharField(choices=[('nl_query', 'NL Query Answer'), ('summary', 'Entity Summary'), ('report', 'Report Section'), ('persona', 'Stakeholder Persona'), ('workplan', 'Workplan'), ('smq', 'SMQ Answer')], max_length=16)),
                ('context_id', models.CharField(blank=True, default='', max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='ingestion.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ner_ai_feedback',
                'indexes': [models.Index(fields=['project', 'context_type'], name='ner_ai_feed_project_43cc72_idx'), models.Index(fields=['user', 'created_at'], name='ner_ai_feed_user_id_f79ac8_idx')],
            },
        ),
    ]
